
name: Deploy SRS to TKE

on:
  push:
    branches:
      - main

jobs:
  k8s:
    name: release-k8s
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up ~/.kube/config for connecting TKE cluster
        uses: TencentCloud/tke-cluster-credential-action@v1
        with:
          secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
          cluster_id: ${{ secrets.TKE_CLUSTER_ID }}
          tke_region: ${{ secrets.TKE_REGION }}

      - name: Switch to TKE context
        run: |
          kubectl config use-context ${TKE_CLUSTER_ID}-context-default

      # Deploy the Docker image to the TKE cluster
      - name: Deploy
        run: |
          kubectl get services -o wide
